### ISSUE TITLE
Where to set name of job listed in print queue

### ISSUE THREAD

**Issue by wluijk** [sandrohanea/PdfiumPrinter#1]
Hello,

I am using PdfiumPrinter in .NET framework but can not find a way to set the name of printjob. It is always listed as "document".
Can we set it on forehand?

Willem Luijk

**Comment by sandrohanea** [comment]
Hi @wluijk,
I just upgraded to version 1.2.0. In this version, I added the possibility to specify the document name in the Print method and I upgraded it to C# 8.0.

You can use it now as following: 
            `printer.Print(printFile, documentName: "with any name");`

Thanks for using it,
If you find it helpful you can give it a star on GitHub.

Kind regards,
Sandro Hanea
