### ISSUE TITLE
NetFramework exception during library load

### ISSUE THREAD

**Issue by sandrohanea** [sandrohanea/PdfiumPrinter#11]
Latest version (1.4.0) is failing if netframework is used using: Verify you have have included the native Pdfium library in your application, or install the default libraries with the bblachon.PDFium Nuget.

Even if you install the package, the library cannot find the native dlls as the path where they are copied is different on netframework.

**Comment by vmiwouter** [comment]
Getting the same error still with 1.4.1 with net 7.0

Seems to work if i install bblanchon.PDFium.Win32 seperatly

**Comment by sandrohanea** [comment]
Hello @vmiwouter ,
Yes, some sort of Pdfium runtime is a dependency, but not enforced at compile time so that each user can decide which version they want to get. The recommended one which should work out of the box, it is indeed: `bblanchon.PDFium.Win32`
