### ISSUE TITLE
The proportion of PDF printing to the printer has been enlarged

### ISSUE THREAD

**Issue by buWenXin** [sandrohanea/PdfiumPrinter#13]
Normally, it should be Image 1, but when printed, the scale has been enlarged, as shown in Image 2

![9bdcd8025acdc171bd7dee88d687065](https://github.com/sandrohanea/PdfiumPrinter/assets/69368870/332f80ee-82ca-4dc3-8b23-4fa3fece851c)

![b1f1a2339abaa3dcbb5423f92219be9](https://github.com/sandrohanea/PdfiumPrinter/assets/69368870/caf2b0a5-b996-4e1b-9cce-8e3c55b90e43)

Can't find an attribute that can set the scaling ratio? What should I do?

**Comment by sandrohanea** [comment]
This is the code that is handling the scaling of the pdf based on the printer's scale and page scale in the PDF:

https://github.com/sandrohanea/PdfiumPrinter/blob/5fd27b02934b5c716c7a163ea60f660ac051887e/PdfiumPrinter/PdfPrintDocument.cs#L167C11-L167C11

You might want to change the printersettings, but not sure what are the values that you want to set for width and height (probably just match your PDF):

```
using var pdfDocument =  PdfDocument.Load(fileName);
using var printDocument = pdfDocument.CreatePrintDocument();
printDocument.PrinterSettings = new PrinterSettings()
{
       PrinterName = printerName
};
printDocument.DefaultPageSettings = new PageSettings(Settings)
{
       Margins = new Margins(0, 0, 0, 0),
       PaperSize =  new PaperSize("My custom PDF paper size, 100, 200)
};
printDocument.PrintController = new StandardPrintController(); // From using System.Drawing.Printing;
printDocument.Print();

```

**Comment by buWenXin** [comment]
> This is the code that is handling the scaling of the pdf based on the printer's scale and page scale in the PDF:
> 
> https://github.com/sandrohanea/PdfiumPrinter/blob/5fd27b02934b5c716c7a163ea60f660ac051887e/PdfiumPrinter/PdfPrintDocument.cs#L167C11-L167C11
> 
> You might want to change the printersettings, but not sure what are the values that you want to set for width and height (probably just match your PDF):
> 
> ```
> using var pdfDocument =  PdfDocument.Load(fileName);
> using var printDocument = pdfDocument.CreatePrintDocument();
> printDocument.PrinterSettings = new PrinterSettings()
> {
>        PrinterName = printerName
> };
> printDocument.DefaultPageSettings = new PageSettings(Settings)
> {
>        Margins = new Margins(0, 0, 0, 0),
>        PaperSize =  new PaperSize("My custom PDF paper size, 100, 200)
> };
> printDocument.PrintController = new StandardPrintController(); // From using System.Drawing.Printing;
> printDocument.Print();
> ```

Thank you very much for providing the code, which solved my problem. But I want to know what caused this problem? Is there any other method besides this one? Because this method requires knowing the size of the PDF, what can be done if the size of the PDF is uncertain

**Comment by sandrohanea** [comment]
Hello,
I'm glad it worked! :)

Depending by the use case, one might use pdfDocument.PageSizes:
```
     if(pdfDocument.PageSizes.Count > 0)
     {
         pd.DefaultPageSettings.PaperSize = new System.Drawing.Printing.PaperSize()
         {
             Width = (int)pdfDocument.PageSizes[0].Width,
             Height = (int)pdfDocument.PageSizes[0].Height
         };

     }
```

However, some people might want to print to the default printer size (not change it) or to specific sizes (but it is possible to retrieve the size of each page in the PDF using PageSizes property).
