### ISSUE TITLE
Is this working with chinese words ??

### ISSUE THREAD

**Issue by ucandoit1010** [sandrohanea/PdfiumPrinter#3]
I haave pdf file but the language is multiple language.
Is this support each language .. zh-cn , zh-tw ???

**Comment by sandrohanea** [comment]
Hi @ucandoit1010!
I checked with some Chinese chars and as long as on the machine we have some fonts for those characters, the library is working as expected.
[ZhCharsPdf.pdf](https://github.com/sandrohanea/PdfiumPrinter/files/5648489/ZhCharsPdf.pdf)
I checked with this pdf.
