### ISSUE TITLE
Print settings are read-only, I need to define paper

### ISSUE THREAD

**Issue by TomLiu-GitHub** [sandrohanea/PdfiumPrinter#5]
Print settings are read-only, I need to define paper
On a stylus printer, there are often different paper types that need to be specified when printing
thinks

**Comment by sandrohanea** [comment]
Hello TomLiu,
Thanks for your interest in PdfiumPrinter.
Indeed, the PageSettings doesn't have a setter but that's ok as you can still define the paper size as follows:
![image](https://user-images.githubusercontent.com/40202887/143767018-9fc1e2cf-5960-415c-9b26-b42ad8f7fbe2.png)
