### ISSUE TITLE
Can not print with signature

### ISSUE THREAD

**Issue by thenhthang** [sandrohanea/PdfiumPrinter#9]
thank you for sharing.  The solution works fine.  I have a pdf file with a digital signature, after printing it does not show this digital signature, do you have a solution?

**Comment by sandrohanea** [comment]
Hey,
I checked and indeed, the underlying library is not printing the digital signature in the pdf when direct printer is used.

However, as a workaround you can use Render method: https://github.com/sandrohanea/PdfiumPrinter/blob/master/PdfiumPrinter/PdfDocument.cs#L270
print the pdf to 1 or multiple bitmaps and than print those bitmaps.

Unfortunately, I don't have any other option, except maybe opening a bug in pdfium here: https://groups.google.com/g/pdfium-bugs

**Comment by sandrohanea** [comment]
I also searched how chromium is printing it (as signature is visible there) and it seems they are doing the same (printing to a bitmap and than send the bitmap to printer):
![image](https://github.com/sandrohanea/PdfiumPrinter/assets/40202887/7381ce37-9fcd-49f2-9710-5e5ca3737b0e)

https://github.com/chromium/chromium/blob/dda78a389143289dc52bd63e9a1e918cc46f0964/pdf/pdfium/pdfium_engine_exports.cc#L279

It is a "temporary" hack but it's like that for at least 5 years.
